FROM python:3.12
WORKDIR /app
RUN apt-get update && apt-get install -y build-essential
RUN apt-get update && apt-get install -y libssl-dev
RUN apt-get update && apt-get install -y libffi-dev
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .


CMD ["python", "main.py"]







